---
title: "Conclusion"
subtitle: "Group #6"
format:
  html:
    embed-resources: true
---

# 1. Which treatment method would be better?

Based on the Kaplan-Meier Survival Curves, treatments labeled as trt=1, trt=2, and trt=3 consistently stay higher than the curve of trt=0 which is ZDV only. These three treatments appear to perform significantly better in terms of patient survival compared to trt=0, whose survival curve is markedly lower. 

This divergence, supported by a p-value of less than 0.0001, suggests that when using treatment ZDV only is less effective at improving patient survival compared to using other treatments. Consequently, any of the treatments trt=1, trt=2, or trt=3 would be preferable over trt=0 for improving survival outcomes in patients. 

After developing Kaplan-Meier Survival Curves only for trt 1,2,3, the corresponding p-value is 0.4, there is no enough evidence for us to conclude that there are significant differences in survival rates among these different treatment graoups. But we can examine that Treatment 1 has comparatively high survival probabilities toward the end of the study.

One potential issue with Kaplan-Meier curves is that they don't account for other important covariates that may influence survival, so by developing a Cox Proportional Hazards Model, after adjusting for different covariates we can conclude that patients taking Treatment 2 appears to have slightly better survival probabilities toward the end of the study compares to Treatment 1 and 3.


# 2. How do patient demographics (e.g. gender, race) influence the effectiveness of different treatment methods on survival outcomes?

By looking at the stratified Kaplan-Meier curves by patient demographic factors, we can conclude that:

1. Gender may significantly influence the survival probability for Treatment 0, with female showing a lightly higher survival probabilities compared to male.

2. With Treatment 1, antiretroviral history (naive vs. experienced) does not significantly impact survival outcomes for patients. However, with Treatment 0, 2, 3, patients with prior ARV treatment show significantly lower survival probabilities compared to naive patients due to the impact of drug resistance.

While other demographic features don't have a significant impact on the effectiveness of different treatment methods.


# 3. What clinical features (e.g., CD4 counts, Karnofsky score) significantly impact survival outcomes for patients undergoing different treatments?

1. For Treatment 1 and 2, there is a strong association between symptom status and survival probabilites, where asymptomatic patients having significantly better survival outcomes.

2. Karnofsky score quantiles significantly impact the survival probabilities for patients using Treatment 2 where higher quantiles associated with higher survival probabilities.

3. There is a consistent and significant impact of CD4 quantiles on survival probabilities across all treatment groups: survival probabilities significantly improve with higher CD4 quartiles.

Tabel: Model Comparasion

| Models  | Accuracy Results  | Important Features |
|--------|--------|--------|
| Logistic Regression  | 0.7608  | "offtrt"  "cd420" "race"  "hemo"  "symptom" "drugs" "gender" "cd820"  "age" "strat" |
| Decision Tree   | 0.7294 | "cd420"   "offtrt"  "age"  "preanti"  "cd40"  "gender" |
| Random Forest  | 0.7686 | "offtrt" "cd420" "preanti" "age" "homo" "z30" "strat" "gender" "cd40" "cd80" |

# 4. What are the most important indicators/features that better give the diagnois result?

By analyzing the important features selected by the three models -- Logistic Regression, Decision Tree, and Random Forest -- it becomes evident that several predictors consistently stand out across all models. These predictors include gender, age, indicator of off-treatment before 96±5 weeks (offtrt), and CD4 at 20±5 weeks. While CD4 counts indicates immune health and play a direct role in survival probabilities, off-treatment status represents treatment adherence, gender and age offer important demographic context that may influence treatment efficacy and survival outcomes.


# 5. what is the best model to predict the diagnosis result?

By comparing the prediction accuracy of these three models, we can conclude that Random Forest Model is the best model to predict the diagnosis result achieving an accuracy of 76.86%. This slightly outperforms Logistic Regression (76.08%) and significantly surpasses the Decision Tree model (72.94%). Additionally, it identifies the most important features (e.g., offtrt, CD4 counts, and age) while achieving robust predictive performance. Therefore, the Random Forest model emerges as the most reliable option for predicting the diagnosis result.



